### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by e2002e** [rpaladin/bug-armory3d-vram-leakage#1]
```
# Fatal error in v8::ToLocalChecked
# Empty MaybeLocal.
```
I couldn't debug it further.

**Comment by rpaladin** [comment]
@e2002e thanks for debugging. @ MoritzBrueckner was able to reproduce those error(s) as well when running from VSCode. However, the issue was discovered to be because currently Kha (and Armory) are missing a check to handle symbols in filenames (notice my images have `&` symbols). In the future a fix will most likely be possible, but for the time being the mentioned workaround must be used.
